import { VERSION } from "./version";

export function isHelpFlag(arg: string): boolean {
  return arg === "--help" || arg === "-h";
}

export function getHelpText(): string {
  return [
    `nextup v${VERSION}`,
    "Resolve a natural-language time expression into one concrete UTC minute.",
    "",
    "Usage:",
    "  nextup [--config <path>] '<request-json>'",
    "  echo '<request-json>' | nextup [--config <path>]",
    "  nextup --help",
    "",
    "Options:",
    "  --config <path>  Optional JSON config for day-part windows.",
    "  -h, --help       Show this help and exit.",
    "",
    "Args:",
    "  <request-json>   Exactly one JSON request, via argv or stdin (not both).",
    "",
    "Request JSON schema:",
    '  {',
    '    "expression": string,',
    '    "window"?: { "start": ISO8601-with-offset-or-Z, "end": ISO8601-with-offset-or-Z },',
    '    "avoid"?: [{ "start": ISO8601-with-offset-or-Z, "end": ISO8601-with-offset-or-Z }],',
    '    "timezone"?: IANA timezone,',
    '    "now"?: ISO8601-with-offset-or-Z,',
    '    "strategy"?: "centered" | "largest-segment-midpoint" | "random" | "earliest" | "latest",',
    '    "random"?: {',
    '      "seed": string,',
    '      "shape"?: "squared" | "linear",',
    '      "spread"?: "narrow" | "medium" | "wide"',
    '    }',
    '  }',
    "",
    "Request rules:",
    '  - expression is required and must be a non-empty string',
    '  - timezone defaults to "UTC"',
    '  - now defaults to current system time',
    '  - strategy defaults to "centered"',
    '  - random is only valid when strategy is "random"',
    '  - random.seed is required when strategy is "random"',
    '  - every interval must satisfy start < end',
    '  - all structured timestamps must include an explicit offset or Z',
    "",
    "Config JSON schema (--config):",
    '  {',
    '    "dayParts": {',
    '      "morning"?: { "start": "HH:MM", "end": "HH:MM" },',
    '      "afternoon"?: { "start": "HH:MM", "end": "HH:MM" },',
    '      "evening"?: { "start": "HH:MM", "end": "HH:MM" },',
    '      "night"?: { "start": "HH:MM", "end": "HH:MM" }',
    '    }',
    '  }',
    "  Rules: local wall-clock 24h times; end may be 24:00; omitted keys use defaults; unknown keys are ignored.",
    "",
    '  - for vague windows already in progress, centered re-centers on the remaining future portion',
    "",
    "Output JSON schema:",
    "  Success:",
    '    {',
    '      "ok": true,',
    '      "result": ISO8601-UTC,',
    '      "resolved_window": { "start": ISO8601-UTC, "end": ISO8601-UTC },',
    '      "now": ISO8601-UTC,',
    '      "anchor": ISO8601-UTC,',
    '      "strategy": "centered" | "largest-segment-midpoint" | "random" | "earliest" | "latest",',
    '      "random"?: { "shape": "squared" | "linear", "spread": "narrow" | "medium" | "wide" }',
    '    }',
    "  Failure:",
    '    { "ok": false, "error": string, "detail": string }',
    "  Failure codes: usage | invalid_input | unparseable | window_past | window_empty | internal",
    "  Normal operation writes exactly one JSON object to stdout.",
    "",
    "Exit codes:",
    "  0   success",
    "  2   invalid_input | unparseable | window_past | window_empty",
    "  64  usage",
    "  70  internal",
    "",
    "Examples:",
    `  nextup '{"expression":"tomorrow morning"}'`,
    `  nextup --config ./nextup.config.json '{"expression":"Friday afternoon","timezone":"Australia/Perth","strategy":"earliest"}'`,
    `  echo '{"expression":"next Tuesday at 2pm","timezone":"America/New_York"}' | nextup`,
    `  nextup '{"expression":"tomorrow morning","strategy":"random","random":{"seed":"task-123"}}'`,
    "",
    "Docs:",
    "  README.md",
    "  docs/spec.md",
    "  docs/ai-assistant-install.md",
  ].join("\n");
}
